# Jump Block Settings
BouncyBlocks:
  # Teleportation may occur with power greater than 3.0!
  # Example: diamond block (ID 57) with jump power 3.7

  "57": 3.0  # Diamond Block
  "41": 2.0  # Gold Block
  "42": 1.0  # Iron Block

  # Inactive Blocks:
  # "7": 7.0   # Bedrock
  # "152": 1.5 # Redstone Block
  # "89": 2.5  # Glowstone Block
  # "1": 1.0   # Stone Block
